version: "3"

services:
    bot:
        build:
            context: .
            dockerfile: bot/Dockerfile
        ports:
            - "8443:8443"
            
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        
        volumes:
            - "./bot/mongodb_data:/data/db"